### ISSUE TITLE
Investigate multiple dashboards workflow

### ISSUE THREAD

**Issue by etolstoy** [rambler-ios/dashramba#19]
We are planning to rotate multiple dashboards - one per project and a couple of global leaderboards. It's emergent to investigate how this feature works, because it may affect jobs implementation.

**Comment by mogol** [comment]
I found this one some weeks ago. I believe, it couldn't affect jobs.
https://github.com/vrish88/sinatra_cyclist

**Comment by etolstoy** [comment]
@mogol thanks, I'll have a look! The question is - if we have the same kind of widget on multiple dashboards (e.g. an average rating widget), how should a job be constructed? Can it send data to widgets on hidden dashboards as well?

**Comment by mogol** [comment]
We have to try. But according to Dashing docs, Yes, it send data to all widgets

**Comment by etolstoy** [comment]
I have this implementation now:

```ruby
project_manager.obtain_all_projects.each do |project|
    reviews = service.obtain_reviews_for_app_id(project.appstore_id)
    widget_name = "appstore_rate_#{project.appstore_id}"
    send_event(widget_name, {
                              'title' => rating.round(2).to_s
                          }
    )
  end
```

**Comment by etolstoy** [comment]
This one was really an easy task.

1. I've implemented cycling, currently between two dashboards. It can be triggered by using URL: `dashboard_url/_cycle?duration=30s`.
2. Dashing updates all widgets, even on hidden dashboards.
